In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.metrics import r2_score

In [2]:
file_path = r"C:\Users\ASUS\OneDrive\Tài liệu\Analysing and Designing Algorithms\Linear Regression\student_data.csv"
df = pd.read_csv(file_path)

In [3]:
#design matrix
df = np.array(df)
X = df[:, [0,2]]
y = df[:,1]

In [4]:
#split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=40)

In [5]:
X_test

array([[2.75, 0.9 ],
       [5.75, 0.4 ],
       [8.5 , 0.8 ],
       [5.  , 0.9 ],
       [1.5 , 0.8 ],
       [4.  , 0.5 ],
       [5.5 , 0.6 ],
       [7.5 , 0.7 ]])

In [6]:
#fit model
model = LinearRegression().fit(X_train, y_train)

In [7]:
y_test

array([5.7, 5.9, 8.3, 6.8, 3.5, 3.1, 4.6, 6.8])

In [8]:
#prediction on test set
y_pred = model.predict(X_test)
y_pred

array([5.08542364, 4.61577114, 7.93361094, 6.37081491, 3.93461588,
       4.05272388, 5.3463529 , 6.92562442])

In [9]:
test = model.predict([[9.0,0.9]])
test

array([8.65595495])